#!/bin/bash

function prepare(){
  sudo apt update -y
  sudo apt upgrade -y
  sudo apt install -y curl git unzip
}

function link_config() {
  for file in ~/.dotfiles/config_files/*; do
    ln -nfs "$file" "$HOME/.$(basename $file)"
  done

  for file in ~/.dotfiles/config/*; do
    ln -nfs "$file" "$HOME/.config/$(basename $file)"
  done
}


function install_pkgs(){
  for installer in ~/.dotfiles/install/*; do source $installer; done
}


case "$1" in
  --install|-i)
    prepare
    link_config
    install_pkgs
    ;;

  --after-download|-a)
    link_config
    install_pkgs
    ;;

  --download|-d)
    prepare
    git clone https://github.com/Danielwsx64/dotfiles.git ~/.dotfiles
    ~/.dotfiles/dotfiles --after-download
    ;;

  *)
    echo
    echo "Uso: $0 OPTIONS"
    echo
    echo 'Options:'
    echo ' -i, --install       Install dotfiles.'
    ;;
esac
