setopt promptsubst

export WORKSPACE='workspace'
export HK_WORKSPACE='hacking_ws'

# load our own completion functions
fpath=(~/.config/zsh/completion /usr/local/share/zsh/site-functions $fpath)

autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit
complete -C '/usr/local/bin/aws_completer' aws

# load custom executable functions
for function in ~/.config/zsh/functions/*; do
  source $function
done

TERM=screen-256color

# makes color constants available
autoload -U colors
colors

# enable colored output from ls, etc
export CLICOLOR=1

# Hooks
autoload -U add-zsh-hook

kitty_title_update() {
  if [[ -n $KITTY_INSTALLATION_DIR ]]; then
    local current_dir=$PWD
    if [[ $current_dir == $HOME ]]; then
      current_dir="~"
    else
      current_dir=${current_dir##*/}
    fi
    command nohup kitten @ set-tab-title $current_dir >/dev/null 2>&1
  fi
}

kitty_title_update
chpwd_functions+=(kitty_title_update)

# history settings
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt APPEND_HISTORY

HISTFILE=~/.zhistory
HISTSIZE=4096
SAVEHIST=4096
HISTORY_IGNORE="(clear|ls |cd |q |fp|gc |gnb )*"

# awesome cd movements from zshkit
setopt autocd autopushd pushdminus pushdsilent pushdtohome cdablevars
DIRSTACKSIZE=5

# Enable extended globbing
setopt extendedglob

# Allow [ or ] whereever you want
unsetopt nomatch

# vi mode
bindkey -v
bindkey "^F" vi-cmd-mode
#bindkey jj vi-cmd-mode

# handy keybindings
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^K" kill-line
bindkey "^R" history-incremental-search-backward
bindkey "^P" history-search-backward
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word

set -o nobeep # no annoying beeps

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# Peepcode theme to make your terminal simple and beautiful
source ~/.config/zsh/themes/peepcode.theme

# Zsh syntax highlight
source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export ERL_AFLAGS="-kernel shell_history enabled -kernel shell_history_file_bytes 2097152"

# bat teme
export FZF_PREVIEW_PREVIEW_BAT_THEME='ansi'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

export ASDF_DATA_DIR="$HOME/.asdf"
export PATH="$ASDF_DATA_DIR/shims:$PATH"

# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.secrets ] && source ~/.secrets
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"

export PATH="$HOME/.bin:$PATH"

export EDITOR=nvim
